### ISSUE TITLE
Should RDF-star and SPARQL-star be 2 separate WGs

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg-charter#1]
Pros:
* historically, they have always been separate WGs
* this would move from one quite ambitious charter to two more reasonable ones
* SPARQL 1.2 would first have to align to RDF 1.1 before tackling RDF-star...
* ... which would require updating [all SPARQL recommendations](https://www.w3.org/2009/sparql/wiki/Main_Page#Recommendations), not just the ones that we touched in the RDF-star CG report

Cons
* my feeling is that people are interested in RDF-star because of SPARQL-star, so separating them might be counter-productive
* this may cause SPARQL to lag behind RDF even more than it is today

**Comment by TallTed** [comment]
It seems a no-brainer to link from here to https://github.com/w3c/sparql-12/ and more specifically https://github.com/w3c/sparql-12/issues/114 ... 

Not to mention, to address the feeling (which I and others have voiced over time) that RDF-star may be more like a fork (or at least, an optional feature) than an evolution of RDF, and SPARQL-star even more so ... 

I am certain that fully specifying RDF-star will require updating all extant RDF 1.1 and SPARQL 1.1 recommendations.  I am thinking that the RDF-star Charter, or *possibly* one of the WG Deliverables, ought to include (or be) a complete list of existing W3C-RDF–related recommendations that are (or are likely to be) impacted by RDF-star and/or SPARQL-star deployment.  I think it likely that this list will include more than SPARQL 1.1, RDF 1.1, and the several RDF 1.1 serializations — but I'm not certain, and am thinking it would be best to address a message to all WG and CG chairs (and possibly participants), *past as well as present*, asking for their input on this list, relative to the groups they facilitated and/or participated in.

**Comment by gkellogg** [comment]
RDF-star/SPARQL-star (and assorted) should indeed be in a single WG, as unwieldy as it may be. Separating the responsibilities would be even messier. That said, the WG should form task groups that focus on specialized parts of the work, and some contributors may only work on a specific task force. It may be that the main WG doesn't have regularly scheduled meetings, except to establish this structure, and coordinate the overall work.

Given this, the charter needs to consider the SPARQL 1.2 work as being in-scope, otherwise where else would the work be done?

The WG should have a formal relationship with the JSON-LD maintenance WG to sort out publishing responsibilities; my thought is that the work should be delegated to the RDF-star WG, as the JSON-LD WG has no active participants.

**Comment by pchampin** [comment]
This was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2021-07-02.html

**Comment by afs** [comment]
I think a single WG would work better because the bulk of the work needed looks like it is aligning with whatever the WG decides about RDF-star in terminology and design. Most of the changes are scoped up by the RDF-star report. 

| Document | Impact |
| ------- | ------ |
| SPARQL 1.1 Overview |  Ideally, add mention of RDF-star |
| SPARQL 1.1 Query Language |  Material from RDF-star report |
| SPARQL 1.1 Update |  Material from RDF-star report |
| SPARQL 1.1 Query Results JSON Format |  Material from RDF-star report |
| SPARQL Query Results XML Format |  Material from RDF-star report |
| SPARQL 1.1 Query Results CSV and TSV Formats |  (below) |
| SPARQL 1.1 Service Description | (below) |
| SPARQL 1.1 Federated Query |  None |
| SPARQL 1.1 Entailment Regimes | None |
| SPARQL 1.1 Protocol | None |
| SPARQL 1.1 Graph Store HTTP Protocol | None |

* CSV format: no change needed
* TSV: format: change follows from Turtle-star.
* Service Description: change not necessary, but may be desirable based on new vocabulary.

The [SPARQL errata](https://www.w3.org/2013/sparql-errata) includes mostly editorial mistakes that simply need content fixes.

**Comment by gkellogg** [comment]
In theory, the JSON-LD Maintenance WG could pop up when there are specific issues. There are, in fact, a number of issues that are continuing to progress for what could be an edited Recommendation, and the WG has the ability to make that happen. And, there are active participants (myself and @pchmampin, at least), but the chair's not been active.

Given that the RDF-Star work is somewhat orthogonal (and the JSON-LD CG does have a note for JSON-LD-Star), it makes sense to lease with the various JSON-LD groups. Publishing an updated or new Recommendation should be coordinated between the two groups.

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#x110
