### ISSUE TITLE
Add text to clearly state that existing RDF 1.1 data will remain valid in syntax and semantics.

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg-charter#27]
As suggested by @afs in https://github.com/w3c/rdf-star-wg-charter/issues/24#issuecomment-1091374907

**Comment by pchampin** [comment]
This was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2022-04-08.html#x097

**Comment by pfps** [comment]
It´s unclear what this issue is actually about and what the invariant is.
Is the invariant that entailment between two RDF graphs is the same in RDF (and extensions of RDF) as it is in RDF* (and extensions of RDF*)?
Is the invariant that adding non-RDF triples to an RDF graph does not add any RDF (or extensions of RDF) consequences?
Is the invariant that queries against an RDF* graph can be interpreted in the same way as queries against an RDF graph?

**Comment by pchampin** [comment]
A paragraph has already been added to the charter to address this action. It was added in 47a0bad  slightly amended in ef8a136. It currently says:

> The group should ensure that any RDF 1.1 data remains valid in this new version. Furthermore, any RDF or RDFS entailment drawn under RDF 1.1 semantics should also remain valid in this new version.

Is that enough clarification?

**Comment by pchampin** [comment]
should have been closed a long time ago... the charter has been accepted in the meantime
