### ISSUE TITLE
Consider adding CSVW specifications

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-star-wg-charter#6]
Although they go further, these specifications also serialize RDF, and include some minor cleanup issues that will never be addressed without an appropriate WG.

**Comment by TallTed** [comment]
Links?

**Comment by pchampin** [comment]
https://www.w3.org/TR/csv2rdf/

**Comment by gkellogg** [comment]
All the related documents are on the GitHub page for the group: https://w3c.github.io/csvw/

* https://www.w3.org/TR/tabular-data-model
* https://www.w3.org/TR/tabular-metadata
* https://www.w3.org/TR/csv2rdf
* https://www.w3.org/TR/csv2json

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://github.com/w3c/rdf-star-wg-charter/issues/6

**Comment by pchampin** [comment]
per https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#a05 
action on myself to check with other W3C team to what extent we can add other specs in scope, time permitting

**Comment by gkellogg** [comment]
We also discussed SHACL, RDFa, RIF, and OWL as specs that a WG might consider updating.

**Comment by pchampin** [comment]
We didn't have time to discuss this during our last call, but here's the outcome of a discussion I had about with @iherman:
* Having a very long list of document marked as "in scope, if we have time" -- this probably won't fly with the AC or W3C management.
* What we could do instead is to provide for a *rechartering*, in case such other documents were proposed to the WG during its lifetime. In other word, if someone came with a mature enough version of CSVW-star during the lifetime of the group, we may recharter to "adopt" that new document.

This makes it explicit that we might touch other documents, but give an opportunity to the AC to give their opinion when/if that happens, rather than requiring a huge wildcard upfront.

**Comment by pchampin** [comment]
this was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2021-12-17.html#x141
